name: minigameapi
version: '${version}'
author: 'JoeMaster_'
main: org.coreplex.MiniGameAPI
api-version: '1.21'
load: POSTWORLD

commands:
  join:
    description: Join an arena
  leave:
    description: Leave an arena
  arenas:
    description: List all registered arenas